// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyASRroFGvnxr71ZAo6r6tRJohK2F8pplM0',
    appId: '1:495256617760:web:959d157e029f6fb77c4d45',
    messagingSenderId: '495256617760',
    projectId: 'safe-drive-a4b50',
    authDomain: 'safe-drive-a4b50.firebaseapp.com',
    storageBucket: 'safe-drive-a4b50.firebasestorage.app',
    measurementId: 'G-R2T4H8J25K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD1kVmhRI2X7bym_Y78FKnXFlUnBh7QjHc',
    appId: '1:495256617760:android:dac4342e1e3fa39f7c4d45',
    messagingSenderId: '495256617760',
    projectId: 'safe-drive-a4b50',
    storageBucket: 'safe-drive-a4b50.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCFm2imyYJpHVXvioBLRnhw34WwK9ZSYcg',
    appId: '1:495256617760:ios:bb791b8af19ad85b7c4d45',
    messagingSenderId: '495256617760',
    projectId: 'safe-drive-a4b50',
    storageBucket: 'safe-drive-a4b50.firebasestorage.app',
    iosBundleId: 'com.example.safeDrive',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCFm2imyYJpHVXvioBLRnhw34WwK9ZSYcg',
    appId: '1:495256617760:ios:bb791b8af19ad85b7c4d45',
    messagingSenderId: '495256617760',
    projectId: 'safe-drive-a4b50',
    storageBucket: 'safe-drive-a4b50.firebasestorage.app',
    iosBundleId: 'com.example.safeDrive',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyASRroFGvnxr71ZAo6r6tRJohK2F8pplM0',
    appId: '1:495256617760:web:b00a6b6409808b6c7c4d45',
    messagingSenderId: '495256617760',
    projectId: 'safe-drive-a4b50',
    authDomain: 'safe-drive-a4b50.firebaseapp.com',
    storageBucket: 'safe-drive-a4b50.firebasestorage.app',
    measurementId: 'G-LS14P3PF6X',
  );
}
